### ISSUE TITLE
when 'Mouse click by tap on screen' option is selected, games that use the mouse will jitter like crazy.

### ISSUE THREAD

**Issue by swagathaur** [rock88/moonlight-nx#10]
First off, great job. This is the best switch game-streaming implementation I've seen so far.

The issue is that games that use the mouse (I tested with GTA V and with CS:GO) will have the screen shake extremely fast whenever this option is ticked. My guess is that it has something to do with how mouse position is constantly set while this option is checked. (Guessing this is the same reason that the cursor on the streaming PC cannot be used at the same time as this option, but can be when its unchecked.)

**Comment by rock88** [comment]
For me in GTA5 mouse also work strange, I will check that soon!

**Comment by rock88** [comment]
I made few fixes in the latest [build](https://github.com/rock88/moonlight-nx/actions?query=workflow%3ABuild) for fix mouse position. Also in some games 'Mouse click by tap' option can break mouse (because send absolute mouse position), default mouse mode (with disabled 'Mouse click by tap' option) should work correctly.
